name: 'Docs'

on:
  push:
    branches:
      - 'main'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    env:
      LISP: sbcl-bin

    steps:
      - uses: actions/checkout@v2
      - uses: 40ants/setup-lisp@v2
      - uses: 40ants/build-docs@v1.3.0
        with:
          asdf-system: logicky-lisp
