name: tests

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:          

  tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        lisp:
          - sbcl-bin
          - ccl-bin
          
    env:
      LISP: ${{ matrix.lisp }}

    steps:
      - uses: actions/checkout@v2
      - uses: 40ants/setup-lisp@v2
        with:
          asdf-system: logicky-lisp
      - uses: 40ants/run-tests@v2
        with:
          asdf-system: logicky-lisp
          coveralls-token: |
            ${{ matrix.lisp == 'sbcl-bin' &&
                matrix.os == 'ubuntu-latest' &&
                secrets.github_token }}
